version: '3.0'
services:  
  sge:
    container_name: sge
    build: .
    command: bash -c "python scripts/init_db.py && uvicorn sge.app:app --host 0.0.0.0 --port 5000 --reload"
    ports:
      - "5000:5000"
    volumes:
      - .:/home/sge
    tty: true
    stdin_open: true
    depends_on:
      - mongo
    networks:
      - mongo-network

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    command: "mongod"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: sge
    networks:
      - mongo-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - mongo-network
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
    depends_on:
      - mongo
    restart: always

networks:
  mongo-network:
    driver: bridge
    